# Generated by Django 5.2 on 2025-04-10 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('activity_type', models.CharField(choices=[('health', 'Saúde'), ('intelligence', 'Inteligência'), ('strength', 'Força'), ('agility', 'Agilidade')], max_length=20, verbose_name='tipo')),
                ('icon', models.CharField(blank=True, help_text='Nome do ícone ou emoji', max_length=50, verbose_name='ícone')),
            ],
            options={
                'verbose_name': 'atividade',
                'verbose_name_plural': 'atividades',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('content', models.TextField(verbose_name='conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('has_reminder', models.BooleanField(default=False, verbose_name='possui lembrete')),
                ('reminder_datetime', models.DateTimeField(blank=True, null=True, verbose_name='data e hora do lembrete')),
                ('reminder_frequency', models.CharField(choices=[('none', 'Nenhum'), ('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], default='none', max_length=10, verbose_name='frequência do lembrete')),
                ('has_checkboxes', models.BooleanField(default=False, verbose_name='possui checkboxes')),
                ('all_checked', models.BooleanField(default=False, verbose_name='todos marcados')),
                ('xp_value', models.PositiveIntegerField(default=5, help_text='Valor de XP entre 1 e 10', verbose_name='valor de XP')),
                ('activities', models.ManyToManyField(blank=True, to='notes.activity', verbose_name='atividades')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Checkbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='texto')),
                ('is_checked', models.BooleanField(default=False, verbose_name='marcado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkboxes', to='notes.note', verbose_name='nota')),
            ],
            options={
                'verbose_name': 'checkbox',
                'verbose_name_plural': 'checkboxes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='rótulo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='notes.note', verbose_name='origem')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='notes.note', verbose_name='destino')),
            ],
            options={
                'verbose_name': 'conexão',
                'verbose_name_plural': 'conexões',
                'unique_together': {('source', 'target')},
            },
        ),
    ]
