# Generated by Django 5.2 on 2025-04-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('activity_type', models.CharField(choices=[('health', 'Saúde'), ('intelligence', 'Inteligência'), ('strength', 'Força'), ('agility', 'Agilidade')], max_length=20, verbose_name='tipo')),
                ('icon', models.CharField(blank=True, help_text='Nome do ícone ou emoji', max_length=50, verbose_name='ícone')),
            ],
            options={
                'verbose_name': 'atividade',
                'verbose_name_plural': 'atividades',
            },
        ),
    ]
